### ISSUE TITLE
update KingAdmin

### ISSUE THREAD

**Issue by stephen144** [hdfelix/ypreg#21]
I think there is a newer version. Do it.

**Comment by pdbradley** [comment]
I bet @hdfelix wishes he had never heard of kingadmin

**Comment by stephen144** [comment]
lol... @pdbradley so you're saying it's not worth it? I think the new version costs $12...

**Comment by pdbradley** [comment]
@stephen144 I just feel like these frameworks at times help in the beginning but eventually you are just fighting them to make simple customizations.

**Comment by stephen144** [comment]
@pdbradley

**Comment by stephen144** [comment]
Yeah... I don't see anything special about it. It might be better to remove it, but I am trying not to do too much 😥
